# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20, verbose_name='评价标签')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonNumA', models.CharField(max_length=20, verbose_name='课程号')),
                ('lessonNumB', models.CharField(max_length=4, verbose_name='课程序号')),
                ('lessonName', models.CharField(max_length=100, verbose_name='课程名')),
                ('lessonCredit', models.IntegerField(default=2, verbose_name='学分')),
                ('lessonAverage', models.FloatField(default=0, verbose_name='平均分')),
                ('lessonPassRate', models.FloatField(default=0, verbose_name='通过率')),
                ('lessonPeople', models.IntegerField(default=0, verbose_name='拥有该课程成绩的人数')),
                ('lessonAverageJudge', models.FloatField(default=5, verbose_name='课程的综合评价分数')),
                ('lessonDisplayLabel', models.TextField(default='', verbose_name='要展示的这门课程的标签,逗号作为分割')),
                ('commentNum', models.IntegerField(default=0, verbose_name='评价人数')),
            ],
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.BooleanField(default=False, verbose_name='本学期课程')),
                ('commented', models.BooleanField(default=False, verbose_name='是否已经评价')),
                ('grade', models.IntegerField(default=0, verbose_name='该门课的成绩')),
                ('lessonJudge', models.IntegerField(default=5, verbose_name='该学生对这门课的评价分数')),
                ('lessonDetailJudge', models.TextField(default='', verbose_name='该学生对这门课的自由评价')),
                ('commentDate', models.DateField(auto_now_add=True, verbose_name='评价时间')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=20, unique=True, verbose_name='标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('studentID', models.CharField(max_length=20, verbose_name='用户名')),
                ('lessonObj', models.ManyToManyField(through='app.LessonComment', to='app.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('school', models.CharField(max_length=40, verbose_name='学院')),
            ],
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='lessonLabelObj',
            field=models.ManyToManyField(to='app.LessonLabel'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='lessonObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lesson'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='studentObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacherObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher', verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teacherObj',
            field=models.ManyToManyField(to='app.Teacher'),
        ),
    ]
