# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='judge',
            field=models.FloatField(default=5, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherDisplayLabel',
            field=models.TextField(default='', verbose_name='要展示的这个老师的标签,逗号作为分割'),
        ),
    ]
